"""initial_schema

Revision ID: 3a9649839855
Revises: 
Create Date: 2026-07-23 20:52:44.360248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a9649839855'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npcs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('npc_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('player_message', sa.Text(), nullable=False),
    sa.Column('npc_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('npc_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('emotion', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recall_count', sa.Integer(), nullable=False),
    sa.Column('last_recalled_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('embedding_id')
    )
    op.create_index('idx_memory_importance', 'memories', ['importance'], unique=False)
    op.create_index('idx_memory_npc', 'memories', ['npc_id'], unique=False)
    op.create_index('idx_memory_player', 'memories', ['player_id'], unique=False)
    op.create_index('idx_memory_state', 'memories', ['state'], unique=False)
    op.create_table('personalities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('npc_id', sa.UUID(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('respect', sa.Integer(), nullable=False),
    sa.Column('warmth', sa.Integer(), nullable=False),
    sa.Column('curiosity', sa.Integer(), nullable=False),
    sa.Column('fear', sa.Integer(), nullable=False),
    sa.Column('loyalty', sa.Integer(), nullable=False),
    sa.Column('aggression', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('aggression BETWEEN 0 AND 100'),
    sa.CheckConstraint('curiosity BETWEEN 0 AND 100'),
    sa.CheckConstraint('fear BETWEEN 0 AND 100'),
    sa.CheckConstraint('loyalty BETWEEN 0 AND 100'),
    sa.CheckConstraint('respect BETWEEN 0 AND 100'),
    sa.CheckConstraint('trust BETWEEN 0 AND 100'),
    sa.CheckConstraint('warmth BETWEEN 0 AND 100'),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npc_id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('npc_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('affinity', sa.Float(), nullable=False),
    sa.Column('trust', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npc_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    op.drop_table('personalities')
    op.drop_index('idx_memory_state', table_name='memories')
    op.drop_index('idx_memory_player', table_name='memories')
    op.drop_index('idx_memory_npc', table_name='memories')
    op.drop_index('idx_memory_importance', table_name='memories')
    op.drop_table('memories')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_table('players')
    op.drop_table('npcs')
    # ### end Alembic commands ###
