"""add memory category

Revision ID: fdc3dc929ea5
Revises: 3a9649839855
Create Date: 2026-07-24 15:35:07.271246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc3dc929ea5'
down_revision: Union[str, Sequence[str], None] = '3a9649839855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "memories",
        sa.Column(
            "category",
            sa.String(length=30),
            nullable=False,
            server_default="other",
        ),
    )

    op.create_index(
        "idx_memory_category",
        "memories",
        ["category"],
        unique=False,
    )

    # Remove the database default after existing rows are populated.
    op.alter_column(
        "memories",
        "category",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_memory_category', table_name='memories')
    op.drop_column('memories', 'category')
    # ### end Alembic commands ###
